### ISSUE TITLE
Unable to create QP.

### ISSUE THREAD

**Issue by aolia-0303** [linux-rdma/perftest#105]
Command that I have tried:
Server:
```
./ib_send_lat  -x 0 -c UD -F -I 0 -a
```

Client:
```
./ib_send_lat  -x 0 -c UD -F -I 0 -a
```

Server output:
```
************************************
* Waiting for client to connect... *
************************************
Unable to create QP.
Failed to create QP.
Couldn't create IB resources
```

Client output:
```
Unable to create QP.
Failed to create QP.
Couldn't create IB resources.
```

I ran “lspci” on the instances where I ran the test and it seems that I have the efa_device installed: 
```
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma]
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.3 Non-VGA unclassified device: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
00:03.0 VGA compatible controller: Amazon.com, Inc. Device 1111
00:04.0 Non-Volatile memory controller: Amazon.com, Inc. Device 8061
00:05.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
00:06.0 Ethernet controller: Amazon.com, Inc. Elastic Fabric Adapter (EFA)
```

Then I hacked into the code, and found that `ibv_create_qp()` (https://github.com/linux-rdma/perftest/blob/master/src/perftest_resources.c#L1848) is not called. 

This is because the `HAVE_IBV_WR_API` flag was not set(https://github.com/linux-rdma/perftest/blob/master/src/perftest_resources.c#L1818)

**Comment by galpress** [comment]
Hey Ao,
Let's take it internally before we open a ticket here, will talk to you offline.

**Comment by meet1744** [comment]
I am facing same issue.
