### ISSUE TITLE
some question about multicast test

### ISSUE THREAD

**Issue by DeruiLiu** [linux-rdma/perftest#111]
i want to test multicast. 1-to-2
server1:
ib_send_bw -d mlx5_1 -F -x 3 -c UD --run_infinitely --report_gbits -M 225.1.1.20
server2:
ib_send_bw -d mlx5_1 -F -x 3 -c UD --run_infinitely --report_gbits -M 225.1.1.20
client:
ib_send_bw -d mlx5_1 -F -x 3 -c UD --run_infinitely --report_gbits -g  -M 225.1.1.20

and in this way, i failed. 

i don't know correct parameters to test multicast. can anyone help me?

**Comment by dimasique1** [comment]
Please, try adding "-g" to all the sides.
Thanks!

**Comment by DeruiLiu** [comment]
> Please, try adding "-g" to all the sides.
> Thanks!

Hi, when I adding "-g" to all the sides. all the sides are servers as below:
```
************************************
* Waiting for client to connect... *
************************************
```
so how can i send messages?  how to set correct parameters to the client.
