### ISSUE TITLE
ib_send_lat doesn't work on AWS EFA card

### ISSUE THREAD

**Issue by garywangcn** [linux-rdma/perftest#113]
I run ib_send_lat on AWS EFA card, but server desn't recv any packet 

Command:
================
client: sudo ./ib_send_lat -d efa_0 -s a 172.31.6.59 -c SRD
server:  sudo ./ib_send_lat -d efa_0 -s a -c SRD

Statistics of EFA hw_counters:
================
client
----------------------
alloc_pd_err :0
alloc_ucontext_err :0
cmds_err :0
completed_cmds :105
create_ah_err :0
create_cq_err :0
create_qp_err :0
keep_alive_rcvd :87
lifespan :12
mmap_err :0
no_completion_cmds :0
rdma_read_bytes :0
rdma_read_resp_bytes :0
rdma_read_wr_err :0
rdma_read_wrs :0
recv_bytes :0
recv_wrs :0
reg_mr_err :0
rx_bytes :0
rx_drops :0
rx_pkts :0
send_bytes :2
send_wrs :1
submitted_cmds :108
tx_bytes :2
tx_pkts :1

server
----------------------
alloc_pd_err :0
alloc_ucontext_err :0
cmds_err :0
completed_cmds :39
create_ah_err :0
create_cq_err :0
create_qp_err :0
keep_alive_rcvd :91
lifespan :12
mmap_err :0
no_completion_cmds :0
rdma_read_bytes :0
rdma_read_resp_bytes :0
rdma_read_wr_err :0
rdma_read_wrs :0
recv_bytes :0
recv_wrs :0
reg_mr_err :0
rx_bytes :0
rx_drops :0
rx_pkts :0
send_bytes :0
send_wrs :0
submitted_cmds :42
tx_bytes :0
tx_pkts :0

**Comment by galpress** [comment]
Hi @garywangcn, can you please try to add the -x 0 (gid index) parameter?

**Comment by garywangcn** [comment]
@galpress thanks for you information, it works.

May I know why the gid index must be configured? And  is there any instruction about how to run perf tools on aws EFA?

**Comment by galpress** [comment]
EFA only works with GIDs addressing, so the -x parameter is mandatory.
By perf tools you mean perftest? I don't think we have special EFA instructions for that.

You can find more information in:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html

**Comment by garywangcn** [comment]
Thanks a lot for your help. @galpress 
I will close this ticket.

Correct command for efa are:
client: sudo ./ib_send_lat -d efa_0 -s a xx.xx.xx.xx -c SRD -x 0
server: sudo ./ib_send_lat -d efa_0 -s a -c SRD -x 0
