### ISSUE TITLE
Should disable PCIe Relaxed Ordering by default?

### ISSUE THREAD

**Issue by Honggang-LI** [linux-rdma/perftest#116]
If perftest was built with a machine which PCIe Relaxed Ordering compliant, and run over two machines which are **_NOT_** PCIe Relaxed Ordering compliant, we will see **significantly performance degradation** for large size message.

https://bugzilla.redhat.com/show_bug.cgi?id=1902855

The perftest of "ib_send_lat RC" test on data size of 4194304 bytes and 8388608 bytes had test time increase of about **250 fold** when compared with the same test on other MLX4 ROCE device, like MLX5 CX-3.

So, should we disable PCIe RO by default, and let the user to enable it or not when run the perftest benchmarks?

Thanks

**Comment by rleon** [comment]
I think that the best way will be to check PCIe RO during perftest execution and disable/enable accordingly.

Thanks

**Comment by Honggang-LI** [comment]
> I think that the best way will be to check PCIe RO during perftest execution and disable/enable accordingly.

Unfortunately, I don't know which C function or library can be used to check PCIe RO. Do you have a suggestion?

In the _"perftest/configure.ac"_ file, PCIe RO will be disabled if specific vendor and device ID was found.
```bash
if [test $IS_FREEBSD = no]; then
        CPU_IS_RO_COMPLIANT=yes
        # Actually this is check for being affected by a known issue
        # with Intel CPUs:
        # https://lore.kernel.org/patchwork/patch/820922/
        intel_no_ro_devices="6f01 6f02 6f03 6f04 6f05 6f06 6f07 6f08 6f09 6f0a 6f0b 6f0c 6f0d 6f0e 2f01 2f02 2f03 2f04 2f05 2f06 2f07 2f08 2f09 2f0a 2f0b 2f0c 2f0d 2f0e"
        for cpu_num in $intel_no_ro_devices; do
                ro_nonsupported=$(lspci -nn | grep -i 8086:$cpu_num)
                if [ test "$ro_nonsupported" ]; then
                        CPU_IS_RO_COMPLIANT=no
                fi
        done
fi

AC_TRY_LINK([
#include <infiniband/verbs.h>],
        [int x = IBV_ACCESS_RELAXED_ORDERING;],[HAVE_RO=yes], [HAVE_RO=no])
AM_CONDITIONAL([HAVE_RO],[test "x$HAVE_RO" = "xyes"])
if [test $HAVE_RO = yes] && [test "x$CPU_IS_RO_COMPLIANT" = "xyes"]; then
        AC_DEFINE([HAVE_RO], [1], [Enable Relaxed Ordering])
fi
```

**Comment by Honggang-LI** [comment]
https://github.com/pciutils/pciutils/blob/master/example.c

We can check the PCI device and vendor IDs as this example.

**Comment by rleon** [comment]
> > I think that the best way will be to check PCIe RO during perftest execution and disable/enable accordingly.
> 
> Unfortunately, I don't know which C function or library can be used to check PCIe RO. Do you have a suggestion?
> 
> In the _"perftest/configure.ac"_ file, PCIe RO will be disabled if specific vendor and device ID was found.
> 
> ```shell
> if [test $IS_FREEBSD = no]; then
>         CPU_IS_RO_COMPLIANT=yes
>         # Actually this is check for being affected by a known issue
>         # with Intel CPUs:
>         # https://lore.kernel.org/patchwork/patch/820922/
>         intel_no_ro_devices="6f01 6f02 6f03 6f04 6f05 6f06 6f07 6f08 6f09 6f0a 6f0b 6f0c 6f0d 6f0e 2f01 2f02 2f03 2f04 2f05 2f06 2f07 2f08 2f09 2f0a 2f0b 2f0c 2f0d 2f0e"
>         for cpu_num in $intel_no_ro_devices; do
>                 ro_nonsupported=$(lspci -nn | grep -i 8086:$cpu_num)
>                 if [ test "$ro_nonsupported" ]; then
>                         CPU_IS_RO_COMPLIANT=no
>                 fi
>         done
> fi
> 
> AC_TRY_LINK([
> #include <infiniband/verbs.h>],
>         [int x = IBV_ACCESS_RELAXED_ORDERING;],[HAVE_RO=yes], [HAVE_RO=no])
> AM_CONDITIONAL([HAVE_RO],[test "x$HAVE_RO" = "xyes"])
> if [test $HAVE_RO = yes] && [test "x$CPU_IS_RO_COMPLIANT" = "xyes"]; then
>         AC_DEFINE([HAVE_RO], [1], [Enable Relaxed Ordering])
> fi
> ```

But we can implement the code above in C, right?
We can dig into /proc/cpuinfo or use libcpuid library instead.

I didn't see how ro check RO explicitly.

Thanks

**Comment by Honggang-LI** [comment]
> But we can implement the code above in C, right?

Yes, https://github.com/linux-rdma/perftest/pull/117

Thanks

**Comment by Honggang-LI** [comment]
Close it as PR #117 had been merged. Thanks
