### ISSUE TITLE
ib_send_bw has very poor incoming performance with split traffic between two nodes.

### ISSUE THREAD

**Issue by cq-cerebras** [linux-rdma/perftest#130]
I have 3 nodes, Mellanox ConnectX-5 ethernet card with RoCe. Nodes are A, B, C.

I start two copies of ib_send_bw on node A (server side):
# taskset -c 4 ib_send_bw -d mlx5_0 -s 4194304 --run_infinitely -p 5001
# taskset -c 5 ib_send_bw -d mlx5_0 -s 4194304 --run_infinitely -p 5002

Then on node B, I start ib_send_bw (client side) to connect to port 5001 on node A:
# taskset -c 1 ib_send_bw -d mlx5_0 -s 4194304 -D 20 --run_infinitely -p 5001 10.254.28.96
again, on node C, I start another ib_send_bw (client side) to connect to port 5002 on node A:
# taskset -c 1 ib_send_bw -d mlx5_0 -s 4194304 -D 20 --run_infinitely -p 5002 10.254.28.96

10.254.28.96 is one of the ip address on node A.

The performance is very poor:
Node B output:
 4194304    4826             0.00               965.20 		   0.000241
 4194304    7695             0.00               1539.00		   0.000385
 4194304    2596             0.00               519.20 		   0.000130
 4194304    7186             0.00               1437.20		   0.000359
 4194304    14261            0.00               2852.20		   0.000713
 4194304    6801             0.00               1360.20		   0.000340
Node C output:
 4194304    2456             0.00               491.19 		   0.000123
 4194304    162              0.00               32.40  		   0.000008
 4194304    4125             0.00               824.99 		   0.000206
 4194304    6177             0.00               1235.39		   0.000309
 4194304    498              0.00               99.60  		   0.000025
 4194304    80               0.00               16.00  		   0.000004

If I either start ib_send_bw on node B or on node C, it can generate very good number:
 4194304    14612            0.00               11689.36		   0.002922
 4194304    14612            0.00               11689.35		   0.002922
 4194304    14612            0.00               11689.35		   0.002922
 4194304    14612            0.00               11689.35		   0.002922
 4194304    14612            0.00               11689.36		   0.002922

Or, I exchange the client/server role (reverse the traffic direction), the BW is evenly split:
 4194304    7306             0.00               5844.68		   0.001461
 4194304    7306             0.00               5844.68		   0.001461
 4194304    7306             0.00               5844.68		   0.001461
 4194304    7309             0.00               5847.08		   0.001462
 4194304    7306             0.00               5844.68		   0.001461

What I hoped is that the BW is evenly split in the poor performance case.
Want to get confirm if this is problem of ib_send_bw itself, or general RoCE problem.

reporter: cq@cerebras.net

**Comment by HassanKhadour** [comment]
Hi cq-cerebras, Sorry for late response.
Can you please try duration also on server side?

**Comment by HassanKhadour** [comment]
Please reopen if reproduce.
