### ISSUE TITLE
Function proc_get_cpu_mhz() is valid for only a few architectures

### ISSUE THREAD

**Issue by vvmitrofanov** [linux-rdma/perftest#133]
It happened that we run your tests on RISC-V arch and found out that some metrics on the final output are zero. Delving into the code showed that proc_get_cpu_mhz() always returns 0, just because this function reads CPU MHz information from /proc/cpuinfo but only a few arches print out this information into this file. To be honest it is difficult to add sth into /proc/cpuinfo.
See requests to solve this problem:
1. https://patchwork.kernel.org/project/linux-arm-kernel/patch/1465333713-14339-2-git-send-email-jon.mason@broadcom.com/#19266527
2. https://patchwork.kernel.org/project/linux-arm-kernel/patch/1386924222-23169-1-git-send-email-vkale@apm.com/  

Why not to get this information from /sys/devices/system/cpu/cpufreq/ ?
It is a portable and clear way to get it.

**Comment by sshaulnv** [comment]
Was the issue resolved after this fix? https://github.com/linux-rdma/perftest/commit/08d1c895359c89ff16e85bc86dbe66fe47c90274

**Comment by vmitrofanov** [comment]
@sshaulnv, yes this patch fix it

**Comment by HassanKhadour** [comment]
Thanks for your contribution!
