### ISSUE TITLE
Use of Device Memory feature in perftests

### ISSUE THREAD

**Issue by BTMichalowicz** [linux-rdma/perftest#143]
Hello! 

I was wondering if the Device Memory API (`ibv_alloc_dm`, `ibv_memcpy_to_dm`, `ibv_reg_dm_mr`, etc.) could be added to the IB perftests as a runtime option? I was trying to implement it myself, but there's a snag about local protection errors that I'm currently debugging (I have an idea, but I just need the time to get to it).

Thank you!

**Comment by HassanKhadour** [comment]
Hi @BTMichalowicz 

It looks good! I'm looking forward to see your code.

Thanks
