### ISSUE TITLE
Release tag versions mismatched with code

### ISSUE THREAD

**Issue by rajachan** [linux-rdma/perftest#146]
I am having a hard time understanding the versioning strategy for perftest. The Github release tags do not seem to line up with what configure sets (and what the built binaries print with --version). For eg, the latest release in Github is tagged `v4.5-0.14` while the code has `6.04`:

https://github.com/linux-rdma/perftest/blob/v4.5-0.14/configure.ac#L32

Any particular reason for the separate versioning schemes?

**Comment by rajachan** [comment]
Ping.

**Comment by HassanKhadour** [comment]
Hi @rajachan 
Sorry for the delay.
We increase the .config versioning after adding couple of new features / fixes while the release tag matches the perftest.spec version and the number of tarballs were created with this version respectively.
,for example v4.5-0.17 indicates 
the following:
*4.5* -perftest.spec version
*0.17*-17 tarballs were created with this perftest.spec version

**Comment by rajachan** [comment]
Alright, thanks.
