### ISSUE TITLE
Please add man pages to all binaries

### ISSUE THREAD

**Issue by bdrung** [linux-rdma/perftest#15]
Currently lintian complains about missing man pages for following binaries:

* ib_atomic_bw
* ib_atomic_lat
* raw_ethernet_burst_lat
* raw_ethernet_bw
* raw_ethernet_lat
* run_perftest_loopback

Please write man pages for these tools.

**Comment by HassanKhadour** [comment]
Better late than never, man pages are ready and will be added in the very near future

**Comment by HassanKhadour** [comment]
Added :)
