### ISSUE TITLE
cannot compile with CX7 and cuda12

### ISSUE THREAD

**Issue by hanyunfan** [linux-rdma/perftest#184]
MLNX_OFED_LINUX-5.8-1.1.2.1 (OFED-5.8-1.1.2)
Ubuntu 20.04
Command: ./autogen.sh && ./configure CUDA_H_PATH=/usr/local/cuda/include/cuda.h && make -j 

Error message:

root@node001:/home/frank/perftest# ./autogen.sh && ./configure CUDA_H_PATH=/usr/local/cuda/include/cuda.h && make -j |& tee -a error.out
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt\~obsolete.m4'
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:55: installing 'config/compile'
configure.ac:36: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ranlib... (cached) ranlib
checking for ANSI C header files... (cached) yes
checking infiniband/verbs.h usability... yes
checking infiniband/verbs.h presence... yes
checking for infiniband/verbs.h... yes
checking sys/random.h usability... yes
checking sys/random.h presence... yes
checking for sys/random.h... yes
checking for ibv_get_device_list in -libverbs... yes
checking for rdma_create_event_channel in -lrdmacm... yes
checking for umad_init in -libumad... yes
checking for log in -lm... yes
checking pci/pci.h usability... yes
checking pci/pci.h presence... yes
checking for pci/pci.h... yes
checking for pci_init in -lpci... yes
checking for ibv_reg_dmabuf_mr in -libverbs... no
checking for cuMemGetHandleForAddressRange in -lcuda... no
checking for efadv_create_qp_ex in -lefa... no
checking for mlx5dv_create_qp in -lmlx5... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/frank/perftest/config/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-am
make[1]: Entering directory '/home/frank/perftest'
  CC       src/perftest_parameters.o
  CC       src/perftest_resources.o
src/perftest_resources.c: In function ‘_new_post_send’:
src/perftest_resources.c:424:10: error: variable ‘mkey_attr’ has initializer but incomplete type
  424 |   struct mlx5dv_mkey_conf_attr mkey_attr = {};
      |          ^~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:424:32: error: storage size of ‘mkey_attr’ isn’t known
  424 |   struct mlx5dv_mkey_conf_attr mkey_attr = {};
      |                                ^~~~~~~~~
src/perftest_resources.c:425:10: error: variable ‘crypto_attr’ has initializer but incomplete type
  425 |   struct mlx5dv_crypto_attr crypto_attr = {};
      |          ^~~~~~~~~~~~~~~~~~
src/perftest_resources.c:425:29: error: storage size of ‘crypto_attr’ isn’t known
  425 |   struct mlx5dv_crypto_attr crypto_attr = {};
      |                             ^~~~~~~~~~~
src/perftest_resources.c:430:33: error: ‘MLX5DV_CRYPTO_STANDARD_AES_XTS’ undeclared (first use in this function)
  430 |   crypto_attr.crypto_standard = MLX5DV_CRYPTO_STANDARD_AES_XTS;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:430:33: note: each undeclared identifier is reported only once for each function it appears in
src/perftest_resources.c:435:3: warning: implicit declaration of function ‘mlx5dv_wr_mkey_configure’ [-Wimplicit-function-declaration]
  435 |   mlx5dv_wr_mkey_configure(ctx->dv_qp[index], ctx->mkey[index], 3, &mkey_attr);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:435:31: error: ‘struct pingpong_context’ has no member named ‘dv_qp’
  435 |   mlx5dv_wr_mkey_configure(ctx->dv_qp[index], ctx->mkey[index], 3, &mkey_attr);
      |                               ^~
src/perftest_resources.c:436:3: warning: implicit declaration of function ‘mlx5dv_wr_set_mkey_access_flags’ [-Wimplicit-function-declaration]
  436 |   mlx5dv_wr_set_mkey_access_flags(ctx->dv_qp[index], IBV_ACCESS_REMOTE_READ |
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:436:38: error: ‘struct pingpong_context’ has no member named ‘dv_qp’
  436 |   mlx5dv_wr_set_mkey_access_flags(ctx->dv_qp[index], IBV_ACCESS_REMOTE_READ |
      |                                      ^~
src/perftest_resources.c:438:3: warning: implicit declaration of function ‘mlx5dv_wr_set_mkey_layout_list’ [-Wimplicit-function-declaration]
  438 |   mlx5dv_wr_set_mkey_layout_list(ctx->dv_qp[index], 1, &sgl);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:438:37: error: ‘struct pingpong_context’ has no member named ‘dv_qp’
  438 |   mlx5dv_wr_set_mkey_layout_list(ctx->dv_qp[index], 1, &sgl);
      |                                     ^~
src/perftest_parameters.c: In function ‘force_dependecies’:
src/perftest_parameters.c:1085:33: error: ‘MLX5DV_BLOCK_SIZE_520’ undeclared (first use in this function); did you mean ‘AES_XTS_BLOCK_SIZE_520’?
 1085 |    user_param->aes_block_size = MLX5DV_BLOCK_SIZE_520;
      |                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                 AES_XTS_BLOCK_SIZE_520
src/perftest_parameters.c:1085:33: note: each undeclared identifier is reported only once for each function it appears in
src/perftest_resources.c:441:41: error: ‘MLX5DV_SIGNATURE_CRYPTO_ORDER_SIGNATURE_BEFORE_CRYPTO_ON_TX’ undeclared (first use in this function)
  441 |    crypto_attr.signature_crypto_order = MLX5DV_SIGNATURE_CRYPTO_ORDER_SIGNATURE_BEFORE_CRYPTO_ON_TX;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:444:41: error: ‘MLX5DV_SIGNATURE_CRYPTO_ORDER_SIGNATURE_AFTER_CRYPTO_ON_TX’ undeclared (first use in this function)
  444 |    crypto_attr.signature_crypto_order = MLX5DV_SIGNATURE_CRYPTO_ORDER_SIGNATURE_AFTER_CRYPTO_ON_TX;
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:448:32: error: ‘true’ undeclared (first use in this function)
  448 |    crypto_attr.encrypt_on_tx = true;
      |                                ^~~~
src/perftest_resources.c:451:32: error: ‘false’ undeclared (first use in this function)
  451 |    crypto_attr.encrypt_on_tx = false;
      |                                ^~~~~
src/perftest_parameters.c:1089:33: error: ‘MLX5DV_BLOCK_SIZE_4048’ undeclared (first use in this function); did you mean ‘AES_XTS_BLOCK_SIZE_4048’?
 1089 |    user_param->aes_block_size = MLX5DV_BLOCK_SIZE_4048;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                 AES_XTS_BLOCK_SIZE_4048
src/perftest_resources.c:466:3: warning: implicit declaration of function ‘mlx5dv_wr_set_mkey_crypto’ [-Wimplicit-function-declaration]
  466 |   mlx5dv_wr_set_mkey_crypto(ctx->dv_qp[index], &crypto_attr);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:466:32: error: ‘struct pingpong_context’ has no member named ‘dv_qp’
  466 |   mlx5dv_wr_set_mkey_crypto(ctx->dv_qp[index], &crypto_attr);
      |                                ^~
src/perftest_resources.c:425:29: warning: unused variable ‘crypto_attr’ [-Wunused-variable]
  425 |   struct mlx5dv_crypto_attr crypto_attr = {};
      |                             ^~~~~~~~~~~
src/perftest_resources.c:424:32: warning: unused variable ‘mkey_attr’ [-Wunused-variable]
  424 |   struct mlx5dv_mkey_conf_attr mkey_attr = {};
      |                                ^~~~~~~~~
src/perftest_resources.c:571:22: error: dereferencing pointer to incomplete type ‘struct mlx5dv_mkey’
  571 |      ctx->mkey[index]->lkey,
      |                      ^~
src/perftest_resources.c: In function ‘ctx_open_device’:
src/perftest_resources.c:1089:10: error: variable ‘login_attr’ has initializer but incomplete type
 1089 |   struct mlx5dv_crypto_login_attr login_attr = {};
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:1089:35: error: storage size of ‘login_attr’ isn’t known
 1089 |   struct mlx5dv_crypto_login_attr login_attr = {};
      |                                   ^~~~~~~~~~
src/perftest_resources.c:1090:10: error: variable ‘attr’ has initializer but incomplete type
 1090 |   struct mlx5dv_context_attr attr = {};
      |          ^~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:1090:30: error: storage size of ‘attr’ isn’t known
 1090 |   struct mlx5dv_context_attr attr = {};
      |                              ^~~~
src/perftest_parameters.c:1093:33: error: ‘MLX5DV_BLOCK_SIZE_4096’ undeclared (first use in this function); did you mean ‘AES_XTS_BLOCK_SIZE_4096’?
 1093 |    user_param->aes_block_size = MLX5DV_BLOCK_SIZE_4096;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                 AES_XTS_BLOCK_SIZE_4096
src/perftest_resources.c:1091:16: error: ‘MLX5DV_CONTEXT_FLAGS_DEVX’ undeclared (first use in this function)
 1091 |   attr.flags = MLX5DV_CONTEXT_FLAGS_DEVX;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:1098:13: warning: implicit declaration of function ‘mlx5dv_open_device’; did you mean ‘ctx_open_device’? [-Wimplicit-function-declaration]
 1098 |   context = mlx5dv_open_device(ib_dev, &attr);
      |             ^~~~~~~~~~~~~~~~~~
      |             ctx_open_device
src/perftest_parameters.c:1097:33: error: ‘MLX5DV_BLOCK_SIZE_4160’ undeclared (first use in this function); did you mean ‘AES_XTS_BLOCK_SIZE_4160’?
 1097 |    user_param->aes_block_size = MLX5DV_BLOCK_SIZE_4160;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                 AES_XTS_BLOCK_SIZE_4160
src/perftest_resources.c:1105:13: warning: implicit declaration of function ‘mlx5dv_crypto_login’ [-Wimplicit-function-declaration]
 1105 |   int ret = mlx5dv_crypto_login(context, &login_attr);
      |             ^~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:1090:30: warning: unused variable ‘attr’ [-Wunused-variable]
 1090 |   struct mlx5dv_context_attr attr = {};
      |                              ^~~~
src/perftest_resources.c:1089:35: warning: unused variable ‘login_attr’ [-Wunused-variable]
 1089 |   struct mlx5dv_crypto_login_attr login_attr = {};
      |                                   ^~~~~~~~~~
src/perftest_parameters.c:1101:33: error: ‘MLX5DV_BLOCK_SIZE_512’ undeclared (first use in this function); did you mean ‘AES_XTS_BLOCK_SIZE_512’?
 1101 |    user_param->aes_block_size = MLX5DV_BLOCK_SIZE_512;
      |                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                 AES_XTS_BLOCK_SIZE_512
src/perftest_resources.c: In function ‘destroy_ctx’:
src/perftest_resources.c:1460:8: warning: implicit declaration of function ‘mlx5dv_dek_destroy’ [-Wimplicit-function-declaration]
 1460 |    if (mlx5dv_dek_destroy(ctx->dek[i]))
      |        ^~~~~~~~~~~~~~~~~~
src/perftest_resources.c:1465:8: warning: implicit declaration of function ‘mlx5dv_destroy_mkey’ [-Wimplicit-function-declaration]
 1465 |    if (mlx5dv_destroy_mkey(ctx->mkey[i]))
      |        ^~~~~~~~~~~~~~~~~~~
src/perftest_resources.c: In function ‘ctx_init’:
src/perftest_resources.c:2160:10: error: variable ‘dek_attr’ has initializer but incomplete type
 2160 |   struct mlx5dv_dek_init_attr dek_attr = {};
      |          ^~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:2160:31: error: storage size of ‘dek_attr’ isn’t known
 2160 |   struct mlx5dv_dek_init_attr dek_attr = {};
      |                               ^~~~~~~~
src/perftest_resources.c:2161:10: error: variable ‘mkey_init_attr’ has initializer but incomplete type
 2161 |   struct mlx5dv_mkey_init_attr mkey_init_attr = {};
      |          ^~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:2161:32: error: storage size of ‘mkey_init_attr’ isn’t known
 2161 |   struct mlx5dv_mkey_init_attr mkey_init_attr = {};
      |                                ^~~~~~~~~~~~~~
src/perftest_parameters.c: In function ‘get_device_max_reads_dc’:
src/perftest_parameters.c:1980:14: warning: implicit declaration of function ‘DEVX_ST_SZ_DW’ [-Wimplicit-function-declaration]
 1980 |  uint32_t in[DEVX_ST_SZ_DW(query_hca_cap_in)] = {};
      |              ^~~~~~~~~~~~~
src/perftest_parameters.c:1980:28: error: ‘query_hca_cap_in’ undeclared (first use in this function)
 1980 |  uint32_t in[DEVX_ST_SZ_DW(query_hca_cap_in)] = {};
      |                            ^~~~~~~~~~~~~~~~
src/perftest_parameters.c:1980:49: error: empty scalar initializer
 1980 |  uint32_t in[DEVX_ST_SZ_DW(query_hca_cap_in)] = {};
      |                                                 ^
src/perftest_parameters.c:1980:49: note: (near initialization for ‘in’)
src/perftest_resources.c:2164:23: error: ‘MLX5DV_CRYPTO_KEY_SIZE_128’ undeclared (first use in this function)
 2164 |   dek_attr.key_size = MLX5DV_CRYPTO_KEY_SIZE_128;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_parameters.c:1981:29: error: ‘query_hca_cap_out’ undeclared (first use in this function)
 1981 |  uint32_t out[DEVX_ST_SZ_DW(query_hca_cap_out)] = {};
      |                             ^~~~~~~~~~~~~~~~~
src/perftest_parameters.c:1981:51: error: empty scalar initializer
 1981 |  uint32_t out[DEVX_ST_SZ_DW(query_hca_cap_out)] = {};
      |                                                   ^
src/perftest_parameters.c:1981:51: note: (near initialization for ‘out’)
src/perftest_resources.c:2166:26: error: ‘MLX5DV_CRYPTO_KEY_PURPOSE_AES_XTS’ undeclared (first use in this function)
 2166 |   dek_attr.key_purpose = MLX5DV_CRYPTO_KEY_PURPOSE_AES_XTS;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_parameters.c:1985:2: warning: implicit declaration of function ‘DEVX_SET’ [-Wimplicit-function-declaration]
 1985 |  DEVX_SET(query_hca_cap_in, in, opcode, MLX5_CMD_OP_QUERY_HCA_CAP);
      |  ^~~~~~~~
src/perftest_parameters.c:1985:33: error: ‘opcode’ undeclared (first use in this function); did you mean ‘opmod’?
 1985 |  DEVX_SET(query_hca_cap_in, in, opcode, MLX5_CMD_OP_QUERY_HCA_CAP);
      |                                 ^~~~~~
      |                                 opmod
src/perftest_parameters.c:1986:33: error: ‘op_mod’ undeclared (first use in this function); did you mean ‘opmod’?
 1986 |  DEVX_SET(query_hca_cap_in, in, op_mod, opmod);
      |                                 ^~~~~~
      |                                 opmod
src/perftest_resources.c:2170:33: error: ‘MLX5DV_MKEY_INIT_ATTR_FLAGS_INDIRECT’ undeclared (first use in this function)
 2170 |   mkey_init_attr.create_flags = MLX5DV_MKEY_INIT_ATTR_FLAGS_INDIRECT |
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_parameters.c:1988:8: warning: implicit declaration of function ‘mlx5dv_devx_general_cmd’ [-Wimplicit-function-declaration]
 1988 |  ret = mlx5dv_devx_general_cmd(context, in, sizeof(in), out,
      |        ^~~~~~~~~~~~~~~~~~~~~~~
src/perftest_parameters.c:1991:16: warning: implicit declaration of function ‘DEVX_GET’ [-Wimplicit-function-declaration]
 1991 |   return (1 << DEVX_GET(query_hca_cap_out, out,
      |                ^~~~~~~~
src/perftest_parameters.c:1992:11: error: ‘cmd_hca_cap’ undeclared (first use in this function)
 1992 |           cmd_hca_cap.log_max_ra_req_dc));
      |           ^~~~~~~~~~~
src/perftest_parameters.c:1981:11: warning: unused variable ‘out’ [-Wunused-variable]
 1981 |  uint32_t out[DEVX_ST_SZ_DW(query_hca_cap_out)] = {};
      |           ^~~
src/perftest_parameters.c:1980:11: warning: unused variable ‘in’ [-Wunused-variable]
 1980 |  uint32_t in[DEVX_ST_SZ_DW(query_hca_cap_in)] = {};
      |           ^~
src/perftest_resources.c:2171:3: error: ‘MLX5DV_MKEY_INIT_ATTR_FLAGS_CRYPTO’ undeclared (first use in this function)
 2171 |   MLX5DV_MKEY_INIT_ATTR_FLAGS_CRYPTO;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/perftest_resources.c:2181:18: warning: implicit declaration of function ‘mlx5dv_dek_create’ [-Wimplicit-function-declaration]
 2181 |    ctx->dek[i] = mlx5dv_dek_create(ctx->context, &dek_attr);
      |                  ^~~~~~~~~~~~~~~~~
src/perftest_resources.c:2192:19: warning: implicit declaration of function ‘mlx5dv_create_mkey’ [-Wimplicit-function-declaration]
 2192 |    ctx->mkey[i] = mlx5dv_create_mkey(&mkey_init_attr);
      |                   ^~~~~~~~~~~~~~~~~~
src/perftest_resources.c:2161:32: warning: unused variable ‘mkey_init_attr’ [-Wunused-variable]
 2161 |   struct mlx5dv_mkey_init_attr mkey_init_attr = {};
      |                                ^~~~~~~~~~~~~~
src/perftest_resources.c:2160:31: warning: unused variable ‘dek_attr’ [-Wunused-variable]
 2160 |   struct mlx5dv_dek_init_attr dek_attr = {};
      |                               ^~~~~~~~
make[1]: *** [Makefile:852: src/perftest_parameters.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:852: src/perftest_resources.o] Error 1
make[1]: Leaving directory '/home/frank/perftest'
make: *** [Makefile:581: all] Error 2

**Comment by sshaulnv** [comment]
Hi,
i tried to reproduce the error and I didn't succeed.
from the output you attached i see that it cant find your cuda library: **checking for cuMemGetHandleForAddressRange in -lcuda... no**

try to check the pointer of the directory you passed using: ll /usr/local/cuda/

**Comment by hanyunfan** [comment]
root@node001:/home/frank/perftest# ll /usr/local/cuda/
total 84
drwxr-xr-x 15 root root   294 Jan  3 11:54 ./
drwxr-xr-x 12 root root   175 Jan  3 11:54 ../
-rw-r--r--  1 root root   160 Oct 24 22:18 DOCS
-rw-r--r--  1 root root 61498 Oct 24 22:18 EULA.txt
-rw-r--r--  1 root root   524 Oct 24 22:18 README
drwxr-xr-x  3 root root  4096 Jan  3 11:54 bin/
drwxr-xr-x  5 root root  4096 Jan  3 11:53 compute-sanitizer/
drwxr-xr-x  3 root root    17 Jan  3 11:53 doc/
drwxr-xr-x  5 root root    53 Jan  3 11:54 extras/
drwxr-xr-x  4 root root    83 Jan  3 11:54 gds/
lrwxrwxrwx  1 root root    28 Oct 24 22:06 include -> targets/x86_64-linux/include/
lrwxrwxrwx  1 root root    24 Nov 30 01:31 lib64 -> targets/x86_64-linux/lib/
drwxr-xr-x  7 root root   209 Jan  3 11:54 libnvvp/
drwxr-xr-x  2 root root    53 Jan  3 11:54 nsightee_plugins/
drwxr-xr-x  3 root root    21 Jan  3 11:54 nvml/
drwxr-xr-x  7 root root    85 Jan  3 11:54 nvvm/
lrwxrwxrwx  1 root root    24 Oct 24 22:32 res -> targets/x86_64-linux/res/
drwxr-xr-x  3 root root    17 Jan  3 11:53 share/
drwxr-xr-x  2 root root   201 Jan  3 11:53 src/
drwxr-xr-x  3 root root    26 Jan  3 11:52 targets/
drwxr-xr-x  2 root root    43 Jan  3 11:54 tools/
-rw-r--r--  1 root root  3112 Dec  3 02:21 version.json

**Comment by hanyunfan** [comment]
Side note: the code can compiled without the Cuda parameter - 
With command: ./autogen.sh && ./configure && make -j

**Comment by sshaulnv** [comment]
I have the exact SAME setup with OFED-5.8-1.1.2, CX7, CUDA 12 and Ubuntu 20.04 and i cant reproduce the issue.
please provide more info about the setup like rdma-core etc.

**Comment by hanyunfan** [comment]
@sshaulnv Could you help to post the results of your ' ./configure CUDA_H_PATH=/usr/local/cuda/include/cuda.h' command.

**Comment by hanyunfan** [comment]
I find out the libcuda.so file in a different folder. once I link it, the compiling is working.

 ln -s /usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so /usr/local/cuda/lib64/libcuda.so

I guess I missed some path before but now it is working.
