### ISSUE TITLE
Question: why qp_access_flags is set to be IBV_ACCESS_REMOTE_WRITE without local write

### ISSUE THREAD

**Issue by changchengx** [linux-rdma/perftest#189]

**Comment by changchengx** [comment]
For RDMA_WRITE operation, after creating RC QP and modify it from RESET to INIT, why ibv_qp_attr.qp_access_flags is set to be  IBV_ACCESS_REMOTE_WRITE without IBV_ACCESS_LOCAL_WRITE?
https://github.com/linux-rdma/perftest/blob/v4.5-0.20/src/perftest_resources.c#L2811
```C
case WRITE : attr.qp_access_flags = IBV_ACCESS_REMOTE_WRITE; break;
```

**Comment by HassanKhadour** [comment]
Hi @changchengx , AFAIK IBV_ACCESS_LOCAL_WRITE is set for the mr in case of write Verb , see create_single_mr in perftest_resources.c
