### ISSUE TITLE
send_lat test fails when rx_depth is less than iteration count

### ISSUE THREAD

**Issue by bryantan-vmware** [linux-rdma/perftest#2]
The reason is this commit: 239df74b0e1526d783726c38fa9c381cf957d693. `ctx->rx_buffer_addr` isn't initialized for the send_lat test. I'm not sure if the fix is just to add `if (user_param->tst == BW)` before it as I'm not clear on what `ctx->rx_buffer_addr` is for.

Apologies if this isn't how issues are reported. Let me know what I should do instead if that is the case.

**Comment by rleon** [comment]
@zoharbmellanox , how do you prefer to get such reports?

**Comment by bryantan-vmware** [comment]
Looks like this has been fixed in 2a8acd06c9bf43712de9bed17652891fece21dc2. Thanks!
