### ISSUE TITLE
configure: error: pciutils header files not found, consider installing pciutils-devel

### ISSUE THREAD

**Issue by xie719040099** [linux-rdma/perftest#207]
Executing./configure under ubuntu22.04 will result in an error: pciutils header files not found, consider installing pciutils devel, but cannot install pciutils-devel under ubuntu

**Comment by HassanKhadour** [comment]
Hi @xie719040099, please install "libpci-dev" package

**Comment by HassanKhadour** [comment]
Please reopen if the issue continues.
