### ISSUE TITLE
Using ib_write_bw as elephant flow in RoCEv2 and the result is not what I expected

### ISSUE THREAD

**Issue by RoyTien** [linux-rdma/perftest#219]
I build a small RoCEv2 network with three BlueField-2 HCAs and one H3C switch, the BlueField-2 network interfaces is 25Gbps.
The ib_write_bw works normal when I run it in two hosts as server and client. The ib_wirte_bw shows the bandwidth is about 23 Gbps which is great. However, if I run ib_write_bw in two hosts as clients and another host as server, the result become weird as shown below: the sum of the two bandwidths is about **5Gbps**.
![image](https://github.com/linux-rdma/perftest/assets/11004295/681e5cb8-2999-4080-b658-c453d26ff6e9)
![image](https://github.com/linux-rdma/perftest/assets/11004295/6c3fae1d-da12-4c0d-8965-43366dcfa740)

RoCEv2 congestion control is about changing the injection rate on a QP.  So the two ib_write_bw can be considered as two elephant flows? Normally the CC algorithm would reduce the flows' rate fairly. Is there anyone who knows why the result is this?

Thank you.

**Comment by mescalin** [comment]
i have the same problem. Did you solve it? Advice would be greatly appreciated
