### ISSUE TITLE
UD is not supported in perftest?

### ISSUE THREAD

**Issue by WoShiAPei** [linux-rdma/perftest#226]
I have found if the number of QPs on client and server is different, the program will crash.
In code it looks like no matter what connection type as input, perftest will make a connection between QP in server and client with 0 - 0, 1-1, 2-2, etc which is not in line with UD.

**Comment by HassanKhadour** [comment]
Hi @WoShiAPei 

You are right, in perftest the qps connection is made in pairs and each qp will be connected to only 1 qp on the other side.

**Comment by WoShiAPei** [comment]
Got it, thank you!
