### ISSUE TITLE
 what does  "num_of_calculated_iters *=num_of_qps" mean in WRITE_BW(infinity) ?

### ISSUE THREAD

**Issue by ecjtusbs** [linux-rdma/perftest#232]
https://github.com/linux-rdma/perftest/blob/c09edf9d2af30ad2d50b564d7e8aa977c05ce40d/src/perftest_parameters.c#L3550C1-L3550C82
When do WRITE_BW(infinity) test, what does  "num_of_calculated_iters *=num_of_qps" mean ?  why should num_of_calculated_iters multiply num_of_qps?  Is not  num_of_calculated_iters  the exactly iter num in this print period?

**Comment by sshaulnv** [comment]
When using run_infinitely the test type is set to DURATION, you can take a look [here](https://github.com/linux-rdma/perftest/blob/3665d9807fec89c92ff49519b4c8c4b2570b93e8/src/perftest_parameters.c#L1385).

with DURATION, the num_of_calculated_iters will be multiplied by 1.

**Comment by ecjtusbs** [comment]
> When using run_infinitely the test type is set to DURATION:
> 
> https://github.com/linux-rdma/perftest/blob/3665d9807fec89c92ff49519b4c8c4b2570b93e8/src/perftest_parameters.c#L1385
> 
> with DURATION, the num_of_calculated_iters will be multiplied by 1.
thanks for your explain.   : )

**Comment by ecjtusbs** [comment]
thank you.
