### ISSUE TITLE
Compilation issue when HAVE_AES_XTS is not defined

### ISSUE THREAD

**Issue by castuardo** [linux-rdma/perftest#243]
In perftest_parameters.c (line 2272), the variable use_write_with_imm_flag is declared subject to HAVE_AES_XTS being defined. But in line 2428, use_write_with_imm_flag is used regardless of HAVE_AES_XTS being defined. This causes compilation issues.

**Comment by HassanKhadour** [comment]
Great catch! thanks, Issue addressed in
https://github.com/linux-rdma/perftest/commit/8f441d3faa3a42a47f40db5ab339ac4ee6538c0d
