### ISSUE TITLE
"Couldn't allocate MR" errors on latest perftest

### ISSUE THREAD

**Issue by larrystevenwise** [linux-rdma/perftest#26]
I get immediate failures on the latest perftest when running ib_send_bw or ib_write_bw over either mlx5 or cxgb4.  git bisect points to this commit as the culprit:

[root@stevo1 perftest]# ./ib_send_bw -a -R -d cxgb4_0 172.16.2.2
Couldn't allocate MR
failed to create mr
Failed to create MR
 Unable to create the resources needed by comm struct
 Unable to perform rdma_client function
 Unable to init the socket connection
[root@stevo1 perftest]# git bisect bad
3d9815e73de2fa9764a170810ec4df4a674fe152 is the first bad commit
commit 3d9815e73de2fa9764a170810ec4df4a674fe152
Author: Zohar Ben Aharon <zoharb@mellanox.com>
Date:   Mon Feb 26 14:14:48 2018 +0200

    Fix for commit a9df5ed7f04484b6838ee2b48246be1ab66513f1

    FreeBSD not supporting contig memory allocation

    Signed-off-by: Zohar Ben Aharon <zoharb@mellanox.com>

:040000 040000 f01b099fc410e017aadb5967c2e0cdb815ba6c52 b3c0d0589c2daff7acc14b752ad1f4175e2d673f M      src
[root@stevo1 perftest]#

**Comment by larrystevenwise** [comment]
The bisect was bad.  I ran it again, and this is the culprit:

1e72cffab4124039280e192ff2907120480b251d is the first bad commit
commit 1e72cffab4124039280e192ff2907120480b251d
Author: Zohar Ben Aharon <zoharb@mellanox.com>
Date:   Sun Nov 19 17:28:59 2017 +0200

    Remove contig support from regular verbs

    Removed the 23 bit enable that refer to contig pages support.
    it is now only supported by exp_verbs.

    Signed-off-by: Zohar Ben Aharon <zoharb@mellanox.com>

:040000 040000 66c85b6d725b1afcdc7072d998b8f031cbfe3c03 ddefc6cd1436ccb1e454700fc56795f82e496959 M      src

**Comment by zoharbmellanox** [comment]
Is the error occurs for RDMA_CM cases only? 
What Os kernel are you running ?

**Comment by bryantan-vmware** [comment]
I'm hitting this issue as well, using vmw_pvrdma. Looks like the problem is that `ctx->is_contig_supported` defaults to SUCCESS, even without exp_verbs, and then `ctx->buf[qp_index]` is set to NULL, which causes ibv_create_mr to fail.

Happens without CM. I'm on a 4.11 kernel, but for vmw_pvrdma I think this would happen regardless of CM/without CM or on a different kernel.

**Comment by larrystevenwise** [comment]
I'm using 4.14.25.

**Comment by zoharbmellanox** [comment]
Thanks again Larry

ive add fix to this Pull request [https://github.com/linux-rdma/perftest/pull/29]
could find your user for Review , will appreciate your feedback

Thanks

**Comment by zoharbmellanox** [comment]
fix added

**Comment by joyceliuExaai** [comment]
Hi All,

I saw the similar issue as well in Kernel 4.18 & Linux 7.5.
I used yum groupinstall "InfinibandSupport" to install IB driver. any solution?

thanks,
Joyce
