### ISSUE TITLE
-a --use_cuda segment error

### ISSUE THREAD

**Issue by yangrudan** [linux-rdma/perftest#283]
# Segmentation Fault During Performance Test Execution

Hello,

I am encountering a segmentation fault when running a performance test using the latest version of the code. 

Here is the command I am using to execute the test:
```bash
./ib_send_bw -d mlx5_cx6_3 -s 4096 --report_gbits --use_cuda=1
```
![截图 2024-08-29 11-01-19](https://github.com/user-attachments/assets/40f88897-3b4a-4718-8cf5-1d68a7caaaf9)

## Erase the error
Then, I changed cuda malloc fucntion from cuMemAlloc to cumemAllocManaged, it works:

![截图 2024-08-29 11-05-18](https://github.com/user-attachments/assets/21a5e378-43c7-4a96-934c-388db96223b0)
![截图 2024-08-28 14-04-22(1)](https://github.com/user-attachments/assets/b260ee91-4339-4298-be44-b312860f5326)
**What's the reason?**

**Comment by sshaulnv** [comment]
On non-coherent platforms like x86, registering CUDA-managed memory via ibv_reg_mr() ensures that the virtual address range is backed by CPU memory pages. In practice, this means you are testing the NIC-to-CPU memory path, rather than the NIC-to-GPU path

**Comment by yangrudan** [comment]
> On non-coherent platforms like x86, registering CUDA-managed memory via ibv_reg_mr() ensures that the virtual address range is backed by CPU memory pages. In practice, this means you are testing the NIC-to-CPU memory path, rather than the NIC-to-GPU path

I think according to the explanation of **cuMemAllocManaged** function, the perftest test is still belong to GPU Direct RDMA.
And why using cuMemAlloc it occured segment err?

https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gb347ded34dc326af404aa02af5388a32
