### ISSUE TITLE
"ib_write_bw" and "ib_read_bw" run into error due to different gid index at both sides

### ISSUE THREAD

**Issue by shuihaihu** [linux-rdma/perftest#44]
I encountered an error when using the following perftest commands to do an environment test:
server side: ib_write_bw -d mlx5_0 -D 10
client side: ib_write_bw -d mlx5_0 -D 10 10.0.13.4

I reinstalled the OFED driver without any modification to the default configuration, but the same error still occurs. I then noticed that these two machines are using different gid index by default. The error is fixed by specifying the gid index as follows:
server side: ib_write_bw -d mlx5_0 -D 10 -x 3
client side: ib_write_bw -d mlx5_0 -D 10 10.0.13.4 -x 3

My question: Why gid index matters? And why the default gid index is different?

**Comment by HassanKhadour** [comment]
Hi shuihaihu,
Gid index is used to link/identify the destination port of the packet, different configurations on the server & client could result in different default gix indexes.
