### ISSUE TITLE
ib_read_bw issue- Swapped VA in RETH

### ISSUE THREAD

**Issue by syedsk** [linux-rdma/perftest#50]
We are testing ibverbs on newly developed IB driver on our microblaze(32 bit) platform with xilinx rdma nic HW. While running ib_read_bw (server on microblaze and client on mlnx connectx-4), I found the client feeding a swapped VA in RETH. I narrowed it down to struct pingpong_dest. The size of this structure is 52bytes on 32bit system and 56bytes on 64bit x86 system with connect-x4.

I did a quick test with __attribute__((packed)) macro on struct pingpong_dest and I now see correct VA coming back from client via RETH.

ib_read_bw  --version shows 5.5. In config.h  I have HAVE_ENDIAN 1.

**Comment by HassanKhadour** [comment]
Hi, Please reopen if Issue still exist
