### ISSUE TITLE
Failed to deallocate PD - Device or resource busy

### ISSUE THREAD

**Issue by tatyana-en** [linux-rdma/perftest#52]
Reported by the UNH-IOL validation group: "When testing with OFED-4.17-rc2 on Kernel 4.17.14 with iWARP, RDMA fails with a variety of vendor cards with all having the same error below on "small/large rdma send. To confirm this is an OFED-4.17-rc2 issue I backtracked to OFED-4.17-rc1 on Kernel 4.17.14 and saw a full pass.

Commands used:

server: ib_send_bw -d i40iw1 -i 1 -s 1 -n 25000 -m 2048 --dont_xchg_versions -R -x 0 -r 510 -F

client: ib_send_bw -d qedr0 -i 1 -s 1 -n 25000 -m 2048 aegaeon-iw.ofa.iol.unh.edu -F --dont_xchg_versions -R -x 0 -r 510

Failed to deallocate PD - Device or resource busy
Couldn't destroy all SEND resources"

It has been confirmed that this is a perftest regression with perftest-4.4-0.5 included with RC2 and OFED 4.17 GA. The perftest-4.4-0.3 that was included with RC1 is working and it also works with OFED 4.17 GA.

**Comment by HassanKhadour** [comment]
Hi tatyana, I see that a fix was merged, please reopen if it reproduces
