### ISSUE TITLE
Unable to run perftest with multiple qp for more than1025 QPs

### ISSUE THREAD

**Issue by bharatpotnuri** [linux-rdma/perftest#54]
I  see the following errors on running  ib_read_bw or ib_write_bw with cxgb4.
It is seen with the commit that adds multiple QP support for rdma-cm `5d1895ae602`.
 
```
[root@saptharishi perftest]# ./ib_write_bw -R -F -n10 -q1026 -s32 --report_gbits 102.1.1.11
RDMA CM event error:
Event: RDMA_CM_EVENT_REJECTED; error: -111.

ERRNO: No such file or directory.
Failed to handle RDMA CM event.
ERRNO: No such file or directory.
Failed to connect RDMA CM events.
ERRNO: No such file or directory.

```
```
rdma-core-24.0-1.el7.x86_64
```

```
# uname -r
4.19.36

```

**Comment by alokprasad** [comment]
@bharatpotnuri Saw this is closed, what this configuration issue?

**Comment by bharatpotnuri** [comment]
> 
> 
> @bharatpotnuri Saw this is closed, what this configuration issue?

Hi @alokprasad 
I found that the issue is due to perftest using shared CQ. I raised a new issue after closing this. Here is the other issue which I raised:
https://github.com/linux-rdma/perftest/issues/78

**Comment by sshaulnv** [comment]
The number QP's should not be a problem.
Try to supply the IPoIB interface as the server IP.
