### ISSUE TITLE
How to specify service level with rdma_cm

### ISSUE THREAD

**Issue by wangshuaizs** [linux-rdma/perftest#56]
Hi,

I want to run `ib_write_bw` with `service level 2` when I am running based on `rdma_cm` (i.e., with `-R`), but it doesn't take effect.  When I remove `-R`, it takes effect. 

So `-R` and `-S` cannot be used simultaneously? How can I specify `service level` with `rdma_cm`?

**Comment by HassanKhadour** [comment]
Hi,
In perftest we can specify the service level only with non rdma_cm traffic.
