### ISSUE TITLE
ib_read_bw over VF generate SegV fault

### ISSUE THREAD

**Issue by jianzzha** [linux-rdma/perftest#64]
#### on server side
ibv_devices
    device          	   node GUID
    ------          	----------------
    mlx5_2          	0000000000000000
    mlx5_0          	506b4b0300285028
    mlx5_3          	0000000000000000
    mlx5_1          	506b4b0300285034

address 1.1.1.2/24 defined for mlx5_2
run: ib_read_bw --report_gbits -s 1048576 -D5 -F -R 

#### on client side
ibv_devices
    device          	   node GUID
    ------          	----------------
    mlx5_0          	248a0703004bf0a8
    mlx5_1          	0000000000000000

address 1.1.1.1/24 defined for mlx5_0
run: ib_read_bw --report_gbits -s 1048576 -D5 -F -R 1.1.1.2

#### result
server (running  ib_read_bw on VF) failed with segV fault when the client tries to connect.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7c7f0dfe64 in ibv_alloc_pd () from /lib64/libibverbs.so.1
(gdb) bt
#0  0x00007f7c7f0dfe64 in ibv_alloc_pd () from /lib64/libibverbs.so.1
#1  0x0000000000417267 in ctx_init (ctx=0x1c75e10, user_param=0x1c75ad0)
    at src/perftest_resources.c:1795
#2  0x0000000000406ca4 in rdma_server_connect (ctx=0x1c75e10, user_param=0x1c75ad0)
    at src/perftest_communication.c:1110
#3  0x00000000004074ea in establish_connection (comm=0x7ffc9c28f320)
    at src/perftest_communication.c:1243
#4  0x0000000000403230 in main (argc=7, argv=0x7ffc9c28f8d8) at src/read_bw.c:115
```

Further debugging:
```
1102		ctx->context = ctx->cm_id->verbs;
(gdb) p ctx->context
$15 = (struct ibv_context *) 0x0
```

**Comment by HassanKhadour** [comment]
Hi jianzzha, I see that the Issue got fixed, Thanks for you collaboration!
