### ISSUE TITLE
perfermance problem about the ib_send_bw test

### ISSUE THREAD

**Issue by shengyang-3390** [linux-rdma/perftest#65]
I test ib_send_bw for two case on ARM services and IB card.
 Case1:numactl -C 64 ib_send_bw -d mlx5_0 -a --iters=1000
 Case2:numactl -C 64 ib_send_bw -d mlx5_0 --size=1024 --iters=1000

Case1 perfermance data:
#bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
1024       1000             0.00               **5544.28**		   5.677340

Case2 perfermance data:
#bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 1024       1000             0.00               **920.13** 		   0.942218

The performance of the case1 is **6 times** of case2 performance. What may cause the performance gap?

**Comment by dimasique1** [comment]
I don't notice such degradation on my setup. What about the other message sizes?
