### ISSUE TITLE
CUDA latency tests

### ISSUE THREAD

**Issue by h4u5** [linux-rdma/perftest#71]
I noticed in perftest_parameters.c:1367: fprintf(stderr," Perftest supports CUDA only in BW tests\n");

It seems to work if I uncomment for read_lat, but I wanted to see if there is a good not to use the test?

**Comment by MoraruMaxim** [comment]
+

**Comment by HassanKhadour** [comment]
Hi Guys, 
I merged "https://github.com/linux-rdma/perftest/commit/98c8b01528e5c5ec713e1ba1fa3720bbca8b9065" so the read & send lat work now with use_cuda.
