### ISSUE TITLE
latency test with duration flag doesn't report min/max/median latency

### ISSUE THREAD

**Issue by manuks88** [linux-rdma/perftest#80]
Hi, when running latency tests with "iterations" (-n) flag, the tool reports min/max/avg/std_dev/99/99.9 latencies. The same latency test when run with "duration" (-D) flag reports only avg latency. How to get the same report for "duration" based tests?
Iteration test : ib_write_lat -F -d mlx5_0 -I 64 -n 100000 -s 1 20.2.1.2
Duration test : ib_write_lat -F -d mlx5_0 -I 64 -D 20 -s 1 20.2.1.2

**Comment by firasj** [comment]
This might be a little tricky because the current implementation holds an array of size "iterations" in order to calculate the mentioned statistics.
On duration mode, such an array doesn't exist because the maximum iterations count (array size) isn't bound.

**Comment by HassanKhadour** [comment]
Thanks @firasj for your answer. closing the Issue
