### ISSUE TITLE
Initializing huge buffers with rand() takes too much time causing iWARP MPA timeout.

### ISSUE THREAD

**Issue by yuvalbason** [linux-rdma/perftest#89]
During MPA negotiation, when passive side gets MPA receive packet, the RDMA-CM stack
creates connection resources (PD, MR, CQ, QP) and initiates MPA offload.
The active side, who initiated the MPA connection sets a timer that times out in case of huge buffers
(initiating those buffers takes more than reasonable MPA timeout).
I think that in this case, perftest should support an option to skip buffer initialization -
	for (i = 0; i < ctx->buff_size; i++) {
				((char*)ctx->buf[qp_index])[i] = (char)rand();

**Comment by dimasique1** [comment]
Yuval,
Thanks for the contribution!
Such a PR will be appreciated.
