### ISSUE TITLE
connect retry fails

### ISSUE THREAD

**Issue by mkalderon** [linux-rdma/perftest#93]
The perftest_communication is written so that the timing between server performing rdma_listen
and client calling rdma_connect is sometimes out of sync. 
The connect flow implements a retry attempt if the rdma_connect fails, but the retry fails
on a return code before and the retry attempt eventually does not happen
repro steps: 
This was exposed on iWARP, where the rdma_listen takes longer. 
Can be easily reproducible by delaying the rdma_listen, or simply running the client before server, no retry occurs. (This also happens on RoCE)

**Comment by HassanKhadour** [comment]
Hi, Sorry for long delay.
Do you see it still exist?

**Comment by HassanKhadour** [comment]
Please reopen if reproduce
